# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "https://wedding-site-cs1.pages.dev"
title = "Wedding site - Kathryn Duffield and Jeroen Jetten"
enableRobotsTXT = true
enableEmoji = true
theme = "custom"

hasCJKLanguage = false     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use
[languages]
  [languages.en]
    contentDir = 'content/english'
    languageName = 'English'
    title = 'Wedsite'
    weight = 1
  [languages.de]
    contentDir = 'content/german'
    languageName = 'Deutsch'
    title = 'geen idee'
    weight = 3
    [languages.de.menu]
  [languages.nl]
    contentDir = 'content/dutch'
    languageName = 'Nederlands'
    title = 'Bruiloft site'
    weight = 2

[markup.goldmark.renderer]
 unsafe = true

[author]                  # essential                     # 必需
  name = "Jeroen Jetten"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

#------------------
# English menu
#------------------
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Information"
  weight = 20
  identifier = "info"
  url = "/information/"
[[menu.main]]
  name = "Schedule"
  weight = 30
  identifier = "schedule"
  url = "/schedule/"
[[menu.main]]
  name = "Hotels"
  weight = 40
  identifier = "hotels"
  url = "/hotels/"
[[menu.main]]
  name = "RSVP"
  weight = 50
  identifier = "rsvp"
  url = "/rsvp/"

#------------------
# Dutch menu
#------------------
[[languages.nl.menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[languages.nl.menu.main]]
  name = "Informatie"
  weight = 20
  identifier = "info"
  url = "/information/"
[[languages.nl.menu.main]]
  name = "Schedule"
  weight = 30
  identifier = "schedule"
  url = "/schedule/"
[[languages.nl.menu.main]]
  name = "Hotels"
  weight = 40
  identifier = "hotels"
  url = "/hotels/"
[[languages.nl.menu.main]]
  name = "RSVP"
  weight = 50
  identifier = "rsvp"
  url = "/rsvp/"

#------------------
# German menu
#------------------
[[languages.de.menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[languages.de.menu.main]]
  name = "Information"
  weight = 20
  identifier = "info"
  url = "/information/"
[[languages.de.menu.main]]
  name = "Schedule"
  weight = 30
  identifier = "schedule"
  url = "/schedule/"
[[languages.de.menu.main]]
  name = "Hotels"
  weight = 40
  identifier = "hotels"
  url = "/hotels/"
[[languages.de.menu.main]]
  name = "RSVP"
  weight = 50
  identifier = "rsvp"
  url = "/rsvp/"

[params]
  since = "2022"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "Wedsite"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["Hugo", "theme","jane"]
  description = "A website celebrating the upcomming mariage of Kathryn Duffield and Jeroen Jetten"

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  toc = false
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'
  
  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  [params.social]                                         # 社交链接
    a-email = "mailto:me@jeroen-jetten.com"
    g-github = "https://github.com/TheTallestJJ/wedding-site"
